(function(){
  const shell=document.querySelector('#appShell');if(!shell)return;
  const home=document.createElement('section');home.id='mobileHome';home.className='mobile-home';home.innerHTML=`
    <header class="home-welcome"><div class="home-photo">Y<span></span></div><div><h2>مرحبًا، <b id="homeUser">يوسف</b></h2><div class="home-balances"><span>🪙 <b id="homeLove">0</b> Love</span><span>✦ <b>980</b> نقطة</span></div></div><button>⌕</button><button>♢<i></i></button></header>
    <article class="home-hero"><div><h1>عِش أجواء الدردشة</h1><p>اقترب ممن تحب<br>واصنع ذكرى بكل لحظة ✨</p><button data-home-route="room">استكشف الآن ‹</button></div></article>
    <div class="quick-grid"><button data-home-route="store"><b>✦</b><strong>نقاطي</strong><small>استبدل نقاطك بمكافآت</small></button><button data-home-route="gifts"><b>🎁</b><strong>الهدايا</strong><small>أرسل هدية لمن تحب</small></button><button data-home-route="store"><b>🛍️</b><strong>المتجر</strong><small>منتجات حصرية بانتظارك</small></button><button data-home-route="wallet"><b>🪙</b><strong>العملات</strong><small>اشحن واحصل على Love</small></button></div>
    <div class="home-section"><header><h2>✦ المتجر والهدايا</h2><button data-home-route="gifts">عرض الكل ‹</button></header><div class="featured-gifts"><article><div>⛵</div><b>رحلة الأحلام</b><span>800 🪙</span></article><article><div>💜</div><b>قلادة السنبلة</b><span>350 🪙</span></article><article><div>🏮</div><b>مصباح السهرة</b><span>200 🪙</span></article><article><div>💝</div><b>باقة رومانسية</b><span>150 🪙</span></article></div></div>
    <div class="home-section"><header><h2>🎁 هدايا النقاط</h2><small>الاستبدال متاح دائمًا</small></header><div class="points-gifts"><article><div>🏰</div><b>قصر الأحلام</b><span>2000 ✦</span></article><article><div>💍</div><b>خاتم الحب</b><span>1000 ✦</span></article><article><div>💗</div><b>قلب</b><span>500 ✦</span></article><article><div>🧸</div><b>دبدوب</b><span>300 ✦</span></article><article><div>🌹</div><b>وردة</b><span>100 ✦</span></article></div></div>
    <div class="home-section"><header><h2>🌐 اكتشف العالم</h2><small>أماكن وذكريات جديدة</small></header><div class="world-cards"><article>بالي</article><article>دبي</article><article>إسطنبول</article><article>باريس</article></div></div>`;
  shell.insertBefore(home,shell.children[1]);
  const bottom=document.createElement('nav');bottom.className='mobile-bottom';bottom.innerHTML=`<button data-home-nav="profile">♙<span>الملف الشخصي</span></button><button data-home-nav="moments">▣<span>اللحظات</span></button><button data-home-nav="games">🎮<span>الألعاب</span></button><button data-home-nav="rooms">♜<span>الغرف</span></button><button data-home-nav="memories">♡<span>الذكريات</span></button><button data-home-nav="cinema">▤<span>سينمتنا</span></button><button class="active" data-home-nav="home">◆<span>الرئيسية</span></button>`;document.body.appendChild(bottom);
  function showHome(){home.style.display='block';document.querySelector('.tabs').style.display='none';document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));bottom.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.homeNav==='home'));scrollTo(0,0)}
  function route(page){home.style.display='none';document.querySelector('.tabs').style.display='flex';const map={rooms:'room',moments:'memories',profile:'store',wallet:'store',gifts:'store'};page=map[page]||page;document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));bottom.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.homeNav===page));scrollTo(0,0)}
  home.querySelectorAll('[data-home-route]').forEach(b=>b.onclick=()=>route(b.dataset.homeRoute));bottom.querySelectorAll('button').forEach(b=>b.onclick=()=>b.dataset.homeNav==='home'?showHome():route(b.dataset.homeNav));
  const observer=new MutationObserver(()=>{if(!shell.classList.contains('ready'))return;document.querySelector('#homeUser').textContent=document.querySelector('#currentName').textContent.replace('الملك ','').replace('الملكة ','');document.querySelector('#homeLove').textContent=document.querySelector('#balance').textContent;showHome()});observer.observe(shell,{attributes:true});
  if(shell.classList.contains('ready'))showHome();
})();
